#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DISTS=$(cat "$SCRIPT_DIR/config/dists.conf")

echo "* Starting Global OS Initialization"

for DIST in $DISTS; do
    echo ">>> Initializing $DIST..."
    "$SCRIPT_DIR/core/dckrbuild-pyinit" "$DIST" --config "$SCRIPT_DIR/config/psha.org.ru.yaml" || exit 1
done

echo "* All OS images are ready!"